apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'Local Jenkins'
  description: 'Local Jenkins to test backstage'
  annotations:
    backstage.io/jenkins-github-folder: 'folder1/job1'
spec:
  type: service
  lifecycle: experimental
  owner: ainouche
